name: Test Runner
on: push

jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker image build -t asana_alart .
      - name: Start container
        run: docker run -it --name asana_container -v $PWD/:/root/ asana_alart bash
      - name: run pytest
        run: pytest
