name: Test Runner
on: push

jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run docker-compose and run pytest
        run: |
          cd .github/workflows/docker
          docker-compose up -d --build
